server:
  port: 8088
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: spring.profiles.active
  jackson:
    date-format: dd MMMM yyyy HH:mm
    time-zone: Asia/Tashkent
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/khantore_crm
    password: this_is_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        enable_lazy_load_no_trans: true